---
apt_cache: 'false' #192.168.242.99' # Apt cache server, set to 'false' to disable
apt_mirror: 'us.archive.ubuntu.com'
domain: 'domain.name'
verbose: true
operatingsystem: 'redhat' # base OS for build node, use 'ubuntu' or 'redhat' 
#node_group: multi_node
